FROM node:14.15-alpine AS build

RUN mkdir -p /app

WORKDIR /app

COPY package.json /app

RUN npm cache clean --force

RUN npm install

COPY . /app

RUN npm run build --prod 

FROM nginx:1.18-alpine

COPY --from=build /app/dist/app /usr/share/nginx/html

